#-------------------------------------------------------------------------------
# Easyparsing file format using .yaml extension for colorization purposes
#-------------------------------------------------------------------------------
# name:         [str]       job name
# cmd:          [str]       binary path
# numprocs:     [number]    number of processes
# umask:        [number]    execution permissions
# working_dir:  [str]       directory from where the process is launched
# autostart:    [0-1]       start the process automatically
# autorestart:  [0-1]       restart the process when it finishes
# exitcodes:    [-number]   expected process exit code(s)
# startretries: [number]    number of restards when it fail or autorestart
# starttime:    [number]    time to wait before checking if the process is alive
# stopsignal:   [0-31]      signal used to stop the process
# stoptime:     [number]    time to wait before checking if the process is terminated
# stdout:       [str]       standart output of the process
# stderr:       [str]       error output of the process
# env:          [_str: str] environment variables to add for the process
#-------------------------------------------------------------------------------

name: ls
cmd: /bin/ls -l /
numprocs: 4
umask: 022
workingdir: .
autostart: 1
autorestart: 0
exitcodes:
-0
-2
startretries: 1
starttime: 300
stopsignal: 4
stoptime: 10
stdout: /dev/ttys002
stderr: /tmp/my_ls.stderr
env:
_STARTED_BY: taskmaster
_ANSWER: 42
